document.getElementById('year').textContent = new Date().getFullYear();

const translations = {
  en: {
    pageTitle:'Website design in The Hague | GOED WEBWERK',pageDescription:'GOED WEBWERK builds fast, professional websites for local businesses in and around The Hague, starting at €249.',
    navWork:'Work',navProcess:'Process',navPrice:'Pricing',navFaq:'Questions',navContact:'Let’s talk',
    heroKicker:'Websites for local businesses',heroLine1:'No big agency.',heroLine2:'A website people notice and trust.',heroIntro:'You speak directly with the person who designs and builds your website. Fast, clear and personal — from The Hague.',heroCta:'See what we make',
    nowLabel:'Now in the studio',inProgress:'In progress',recentDelivery:'Recently delivered',liveNow:'Live',hospitalitySite:'Hospitality website',days:'days',delivery:'average delivery time',languages:'languages',languageList:'Dutch · English · Chinese',startingAt:'starting price',liveEvkerk:'Live · evkerk.nl',liveKaida:'Live · kaida.nl',liveTaalvia:'Live · taalvia.nl',liveMenZegt:'Live · menzegt.nl',
    madeFor:'Industries we know',horeca:'Hospitality',construction:'Construction',salons:'Hair salons',nonprofits:'Foundations & non-profits',localServices:'Local services',
    selectedWork:'Selected work',workTitle:'Real websites for real organisations.',workIntro:'Not design exercises, but work used every day by customers, members and visitors.',churchNonprofit:'Church & non-profit',evkerkTitle:'Evangelische Kerk Nederland',evkerkVisualEyebrow:'Church website',evkerkVisual:'A welcoming church community',evkerkDesc:'A bilingual church website with two locations, current sermons and activities managed by the church itself.',bilingual:'Bilingual',selfManaged:'Content management',viewLive:'View live website',
    constructionInterior:'Construction & interiors',kaidaTitle:'Kaida',kaidaVisualEyebrow:'Renovation & interiors',kaidaVisual:'Craftsmanship, clearly presented',kaidaDesc:'A project website that showcases craftsmanship and lets the client upload photos and videos independently.',learningPlatform:'Digital learning platform',taalviaTitle:'Taalvia',taalviaVisualEyebrow:'Language platform',taalviaVisual:'Learn Dutch with Taalvia',taalviaDesc:'One multilingual ecosystem for daily Dutch learning and practice.',menZegtTitle:'Men Zegt Snackbar',menZegtDesc:'A new website with a clear menu, opening hours and practical visitor information.',menu:'Menu',mobile:'Mobile',viewPreview:'View client preview',
    howItWorks:'How it works',processTitle:'You know your business. I make it clear on screen.',processIntro:'No account manager and no complicated handover. We discuss what customers need to see and do; then you quickly receive something concrete.',discussProject:'Discuss your project',step1Title:'Listen first',step1Text:'We turn your business, customers and main goal into a clear plan.',step2Title:'Make it visible',step2Text:'You quickly receive a real first version. Not an abstract story, but something you can respond to.',step3Title:'Online and available',step3Text:'After launch, you keep calling one person for technology, maintenance and changes.',
    whyGoed:'Why GOED WEBWERK',aboutTitle:'Small enough to stay personal. Serious enough to do it properly.',aboutText:'You work directly with the person making your website. Clear agreements upfront, attention to mobile and Google, and someone who remains available after launch.',basedIn:'Based in The Hague',directContact:'Always direct contact',focusTitle:'One project at a time',focusText:'To protect the quality of both design and delivery, we work with one client project at a time. Once all required materials are complete and, where applicable, the first payment has been received, the website is usually ready within 7–14 working days.',
    clearPrice:'Clear pricing',priceTitle:'See upfront what fits your business.',priceIntro:'From a strong single page to a website with content management. We confirm the fixed price before we begin.',from:'from',month:'month',careTextShort:'hosting, security, backups and small updates',starterLevel:'Starter',businessLevel:'Business',professionalLevel:'Professional',customLevel:'Custom',starterTitle:'One-page website',starterExample:'For example: nail studio, hairdresser or independent service provider',starterFeature1:'Services, prices and contact on one clear page',starterFeature2:'Mobile design, map and booking button',starterFeature3:'Basic Google visibility',businessTitle:'Website for local businesses',businessExample:'Like Men Zegt: menu, opening hours, location and direct actions',businessFeature1:'Multiple clear sections or pages',businessFeature2:'Built around calls, visits, orders or bookings',businessFeature3:'Professional presentation on mobile and desktop',professionalTitle:'Extended business website',professionalExample:'Like Kaida: multiple pages, projects and content management',professionalFeature1:'Extensive project or service presentation',professionalFeature2:'Update photos, videos or content yourself',professionalFeature3:'A structure designed for growth',popularChoice:'Popular choice',customTitle:'Custom website with management tools',customExample:'Like the church website: multilingual, sermons, activities and extensive management',customFeature1:'Custom functions and structure',customFeature2:'Multiple content types and administrators',customFeature3:'Quoted after a clear requirements review',careTextCustom:'management, hosting, security, backups and support',priceNote:'All prices are one-time development fees. The monthly amount covers hosting and ongoing management. Extra languages: second language +€99, third language +€79.',handoverLink:'Who owns the website, and can I take it with me?',handoverLabel:'Ownership and transfer',handoverTitle:'Your business stays yours.',handoverIntro:'The domain and business accounts always remain in your name. If you end our monthly service, you can choose:',handoverContinue:'Continue with maintenance. Hosting, security, backups and small updates remain covered.',handoverLeave:'Take the website with you. On request, you receive a free standard export of the website files and the content you supplied.',handoverNote:'Technical migration to another hosting provider, paid licences and third-party services are not included in the standard export and can be quoted separately.',handoverDone:'Got it',freeIntake:'Request a free consultation',
    faqLabel:'Frequently asked questions',faqTitle:'Clarity first. Then we build.',q1:'Who owns the domain and website?',a1:'The domain and business accounts remain in your name. You are never locked in because someone else controls access.',q2:'How quickly can my website go live?',a2:'A clear business website is usually ready within 7–14 working days. Timing mainly depends on copy, photos and feedback.',q5:'When does the timeline begin, and how do revision rounds work?',a5:'The timeline begins once all required materials are complete and, where applicable, the first payment has been received. The quote includes two consolidated revision rounds. After receiving the preview, please submit all feedback together within three working days. If materials or feedback are delayed by more than five working days, the project will be paused and rescheduled according to the availability at that time.',q3:'What if I do not have good copy or photos yet?',a3:'I help clarify the content and structure. We can create missing copy together and agree upfront on the photos needed.',q4:'How much does a multilingual website cost?',a4:'The basic website package includes one language. A second language costs an additional €99; a third language costs a further €79. For a standard small brochure website, this includes organising the translated content, a language switcher, layout adjustments for each language and basic SEO setup. Websites with a large amount of content or specialist terminology, and projects requiring professional human translation, are quoted separately based on the amount of content.',
    meet:'Let’s talk',contactTitle:'What would you like your website to achieve?',contactIntro:'Tell us briefly about your business. You will receive a personal reply — without sales pressure or obligation.',sendWhatsapp:'Send a message ↗',communication:'We can communicate in Dutch, Chinese or English.',name:'Name',company:'Company',email:'Email',emailShort:'Email',messageLabel:'Tell us briefly what you need',sendRequest:'Send my enquiry',privacy:'Your details are only used to contact you.',namePlaceholder:'Your name',companyPlaceholder:'Company name',messagePlaceholder:'For example: a website for my restaurant...'
  },
  zh: {
    pageTitle:'海牙网站制作 | GOED WEBWERK',pageDescription:'GOED WEBWERK 为海牙及周边本地商家制作快速、专业、适配手机的网站，价格 €249 起。',
    navWork:'案例',navProcess:'流程',navPrice:'价格',navFaq:'常见问题',navContact:'聊聊项目',
    heroKicker:'为荷兰本地商家制作网站',heroLine1:'不是大型设计公司。',heroLine2:'但网站值得被人看见。',heroIntro:'你直接和设计、制作网站的人沟通。快速、清楚、有人情味——立足海牙。',heroCta:'看看我们做的网站',
    nowLabel:'正在制作',inProgress:'正在制作',recentDelivery:'近期上线',liveNow:'已上线',hospitalitySite:'餐饮网站',days:'天',delivery:'平均交付时间',languages:'种语言',languageList:'荷兰语 · 英语 · 中文',startingAt:'起步价格',liveEvkerk:'已上线 · evkerk.nl',liveKaida:'已上线 · kaida.nl',liveTaalvia:'已上线 · taalvia.nl',liveMenZegt:'已上线 · menzegt.nl',
    madeFor:'我们熟悉的行业',horeca:'餐饮',construction:'装修与施工',salons:'美容美发',nonprofits:'基金会与非营利机构',localServices:'本地服务商',
    selectedWork:'项目案例',workTitle:'我们做过的项目。',workIntro:'教会、本地商家、餐饮和数字产品，下面都是已经交付或正在使用的项目。',churchNonprofit:'教会与非营利机构',evkerkTitle:'荷兰福音教会',evkerkVisualEyebrow:'双语教会网站',evkerkVisual:'欢迎每一个人的教会',evkerkDesc:'整合两个聚会点、最新讲道和活动，并支持教会自主更新内容。',bilingual:'双语',selfManaged:'自主管理',viewLive:'查看在线网站',
    constructionInterior:'装修与室内设计',kaidaTitle:'凯达装修',kaidaVisualEyebrow:'装修与室内设计',kaidaVisual:'让专业手艺被看见',kaidaDesc:'集中展示装修项目与专业手艺，并支持客户自行上传图片和视频。',learningPlatform:'数字学习平台',taalviaTitle:'Taalvia 荷兰语学习',taalviaVisualEyebrow:'荷兰语学习平台',taalviaVisual:'每天学一点，真正用起来',taalviaDesc:'整合日常荷兰语学习与练习的多语言产品生态。',menZegtTitle:'Men Zegt 薯条店',menZegtDesc:'整合清晰菜单、营业时间和到店信息的本地餐饮网站。',menu:'在线菜单',mobile:'手机适配',viewPreview:'查看客户预览',
    howItWorks:'我们怎么做',processTitle:'你最懂自己的生意，我们负责把它做清楚。',processIntro:'先听你真正想解决什么，再看客户需要看到什么、做什么。很快给你一个可以直接看的版本，边看边改，不绕弯。',discussProject:'聊聊你的需求',step1Title:'先把事情听明白',step1Text:'弄清你的业务、客户和最重要的目标，先把方向定下来。',step2Title:'尽快做出第一版',step2Text:'不先讲一堆概念，直接做出可以看的版本，再根据你的反馈调整。',step3Title:'上线以后也找得到人',step3Text:'维护、修改和技术问题都还是同一个人负责，不用每次重新解释一遍。',
    whyGoed:'为什么是 GOED WEBWERK',aboutTitle:'小团队，直接沟通；该认真做的，一点不少。',aboutText:'从第一次沟通到上线，你都直接和实际做网站的人联系。范围、价格和时间提前说清楚；上线后要改东西、处理技术问题，也还是找同一个人。',basedIn:'海牙本地',directContact:'直接和制作者沟通',focusTitle:'一次只做一个项目',focusText:'我们不会同时塞很多项目。资料齐全、项目启动后，常规网站一般在 7–14 个工作日内完成。',
    clearPrice:'价格透明',priceTitle:'先把预算和范围说清楚。',priceIntro:'从简单单页到带后台的定制网站，开始之前先确认做什么、多少钱。',from:'起',month:'月',careTextShort:'托管、安全、备份和小幅修改',starterLevel:'基础',businessLevel:'商家',professionalLevel:'专业',customLevel:'定制',starterTitle:'单页展示网站',starterExample:'例如：美甲店、理发店或个人服务',starterFeature1:'服务、价格和联系方式集中在一个页面',starterFeature2:'手机适配、地图和预约按钮',starterFeature3:'基础 Google 搜索优化',businessTitle:'本地商家网站',businessExample:'如 Men Zegt 薯条店：菜单、营业时间、地址与直接操作入口',businessFeature1:'多个清晰内容区或页面',businessFeature2:'围绕电话、到店、下单或预约设计',businessFeature3:'手机和电脑端专业呈现',professionalTitle:'专业企业网站',professionalExample:'如凯达装修：多页面、项目案例和内容后台',professionalFeature1:'完整展示项目或服务',professionalFeature2:'可自行更新图片、视频或内容',professionalFeature3:'方便以后继续扩充',popularChoice:'常见选择',customTitle:'高级定制与后台管理',customExample:'如福音教会网站：多语言、讲道、活动和复杂后台',customFeature1:'按照实际工作流程定制功能',customFeature2:'支持多种内容和管理人员',customFeature3:'梳理需求后提供固定报价',careTextCustom:'后台维护、托管、安全、备份和支持',priceNote:'以上均为一次性制作费；月费包含托管和持续维护。增加第2种语言 +€99，第3种语言再加 €79。',handoverLink:'网站归谁，可以带走吗？',handoverLabel:'网站归属与移交',handoverTitle:'你的生意始终属于你。',handoverIntro:'域名和企业账号始终登记在你名下。结束我们的月度服务时，你可以选择：',handoverContinue:'继续维护。托管、安全、备份和小幅修改继续由我们负责。',handoverLeave:'带走网站。提出要求后，可免费获得网站文件及你提供内容的标准导出。',handoverNote:'迁移至其他托管服务商的技术操作、付费许可证及第三方服务不包含在标准导出内，可另行报价。',handoverDone:'明白了',freeIntake:'聊聊你的项目',
    faqLabel:'常见问题',faqTitle:'先说清楚，再开始。',q1:'域名和网站归谁所有？',a1:'域名和企业账号始终登记在你名下，不会因为别人掌握权限而被绑定。',q2:'网站多久可以上线？',a2:'一般企业网站通常可在 7–14 个工作日内完成，具体取决于文字、照片和反馈是否及时。',q5:'制作周期和修改如何计算？',a5:'制作周期从所需资料齐全，并在适用情况下收到首笔付款后开始计算。报价包含两轮集中修改。预览稿提交后，客户应在 3 个工作日内集中反馈；若资料或反馈延迟超过 5 个工作日，项目将暂停，并根据当时档期重新安排。',q3:'如果我还没有合适的文字或照片怎么办？',a3:'我会先帮你理清内容和顺序，缺少的文字可以一起整理，照片需要什么也会提前说明。',q4:'多语言网站如何收费？',a4:'基础网站套餐仅包含 1 种语言。增加第 2 种语言：+€99；增加第 3 种语言：再加 €79。普通小型展示网站的价格包含翻译整理、语言切换、各语言页面排版适配及基础 SEO 设置。若网站内容较多、涉及专业术语，或客户要求人工专业翻译，则根据内容量单独报价。',
    meet:'聊聊需求',contactTitle:'说说你想解决什么，我们一起看看怎么做。',contactIntro:'告诉我们你的业务和目标。网站、AI、自动化都可以聊，我们会直接告诉你适不适合、怎么做。',sendWhatsapp:'发送消息 ↗',communication:'可使用荷兰语、中文或英语沟通。',name:'姓名',company:'公司或店铺',email:'电子邮箱',emailShort:'电子邮箱',messageLabel:'简单说说你需要什么',sendRequest:'发送咨询',privacy:'你的资料只用于回复本次咨询。',namePlaceholder:'你的姓名',companyPlaceholder:'公司或店铺名称',messagePlaceholder:'例如：为我的餐厅制作一个网站……'
  }
};

Object.assign(translations.en,{
  ownKicker:'Own products',ownTitle:'More than websites.',ownIntro:'Sometimes we also build our own digital products.',
  ownTypeTaalvia:'Own digital product',ownTaalviaDesc:'A language platform where learning, interaction and a digital world come together.',
  ownTypeSynaven:'Own technology platform',ownSynavenDesc:'Our own technology platform for controlled AI systems, with products for operations, customer contact and travel technology.',ownView:'View project'
});
Object.assign(translations.zh,{
  ownKicker:'自有产品',ownTitle:'不止是网站。',ownIntro:'我们也会开发自己的数字产品。',
  ownTypeTaalvia:'自有数字产品',ownTaalviaDesc:'一个把语言学习、互动体验和数字世界连接起来的平台。',
  ownTypeSynaven:'自有技术平台',ownSynavenDesc:'一个用于可控 AI 系统的自有技术平台，覆盖运营、客户沟通和旅行科技等产品方向。',ownView:'查看项目'
});


Object.assign(translations.en,{serviceIndexKicker:'Who we build for',serviceIndexTitle:'A website shaped around how your customers search.',service1Title:'Website design in The Hague',service1Text:'For local businesses that want to look professional and clear online.',service2Title:'Website for hospitality',service2Text:'Menu, opening hours, location and contact made clear on mobile.',service3Title:'Website for foundations & non-profits',service3Text:'Clear for new visitors, members and volunteers.',serviceReadMore:'Read more →'});
Object.assign(translations.zh,{serviceIndexKicker:'常见项目',serviceIndexTitle:'我们常做的几类网站。',service1Title:'海牙本地商家网站',service1Text:'适合想把服务、位置和联系方式讲清楚的本地商家。',service2Title:'餐饮与门店网站',service2Text:'菜单、营业时间、地址和预订入口，手机上打开就能找到。',service3Title:'教会、基金会与非营利网站',service3Text:'活动、资讯、联系方式和重要内容，让不同访客都能快速找到。',serviceReadMore:'查看方案 →'});

Object.assign(translations.en,{liveSunny:'Preview project · Rijswijk',beautyOnePage:'Beauty · one-page website',sunnyDesc:'A clear, practical website for a local nail studio. Customers can quickly find prices, opening hours and parking information, then call directly to book.',basicOnePage:'Basic · €249',viewProject:'Preview project · Rijswijk'});
Object.assign(translations.zh,{liveSunny:'预览项目 · Rijswijk',beautyOnePage:'美甲美容 · 单页网站',sunnyDesc:'为本地美甲店制作的清晰实用型网站。顾客可以快速查看价格、营业时间和停车信息，并直接电话预约。',basicOnePage:'基础 · €249',viewProject:'预览项目 · Rijswijk'});

Object.assign(translations.en,{noDeposit39:'Or €39 per month in the first year · €0 deposit · includes hosting, security, backups and small updates',noDeposit59:'Or €59 per month in the first year · €0 deposit · includes hosting, security, backups and small updates',noDeposit79:'Or €79 per month in the first year · €0 deposit · includes hosting, security, backups and small updates',noDeposit139:'Or €139+ per month in the first year · €0 deposit · includes management, hosting, security, backups and support',after12Months:'After 12 months:',priceNote:'Choose a one-off payment or €0 deposit with a minimum term of 12 months. After that, only the lower monthly hosting and management fee applies. Extra languages: second language +€99, third language +€79.'});
Object.assign(translations.zh,{noDeposit39:'或第一年每月 €39 · €0 首付 · 包含托管、安全、备份和小幅修改',noDeposit59:'或第一年每月 €59 · €0 首付 · 包含托管、安全、备份和小幅修改',noDeposit79:'或第一年每月 €79 · €0 首付 · 包含托管、安全、备份和小幅修改',noDeposit139:'或第一年每月 €139+ · €0 首付 · 包含管理、托管、安全、备份和支持',after12Months:'满12个月后：',priceNote:'可选择一次性支付，或 €0 首付、最短12个月。满12个月后只收较低的托管维护月费。增加第2种语言 +€99，第3种语言再加 €79。'});


Object.assign(translations.en,{navSkills:'AI Skills',skillsHomeTitle:'Give AI a workflow, not just a prompt.',skillsHomeIntro:'New reusable AI workflows for design, writing, business and productivity. Starting small, but useful right away.',skillsCard1:'Have AI review a page like a senior designer and return concrete improvements ordered by impact.',skillsCard2Title:'Natural Dutch',skillsCard2:'Turn stiff or translated text into natural Dutch without losing meaning or tone.',skillsCard3Title:'Meeting → Action Plan',skillsCard3:'Turn notes or transcripts into decisions, tasks, owners and open points without inventing information.',skillsHomeCta:'Browse all AI Skills'});
Object.assign(translations.zh,{navSkills:'AI Skills',skillsHomeTitle:'我们整理了一套 AI Skills 库。',skillsHomeIntro:'设计、写作、SEO、研究和效率等 213 个工作流，可以按分类查找、复制或下载。',skillsCard1:'让 AI 像资深设计师一样检查页面，并按影响大小给出具体修改建议。',skillsCard2Title:'自然荷兰语',skillsCard2:'把生硬或翻译腔的文字改成自然荷兰语，同时保留原意与语气。',skillsCard3Title:'会议 → 行动计划',skillsCard3:'把会议记录整理成决定、任务、负责人和待确认事项，不让 AI 自己脑补。',skillsHomeCta:'查看全部 AI Skills'});

// Keep the Dutch source copy as a real language dictionary. Without this,
// switching back from English or Chinese leaves the previous language on screen.
translations.nl = {};
document.querySelectorAll('[data-i18n]').forEach(el=>{translations.nl[el.dataset.i18n]=el.textContent.trim()});
document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{translations.nl[el.dataset.i18nPlaceholder]=el.placeholder});
translations.nl.pageTitle=document.title;
translations.nl.pageDescription=document.querySelector('meta[name="description"]').content;
translations.nl.priceNote='Kies eenmalig betalen of €0 aanbetaling met een minimale looptijd van 12 maanden. Daarna geldt alleen het lagere maandbedrag voor hosting en beheer. Extra talen: tweede taal +€99, derde taal +€79.';

function applyLanguage(lang){const dict=translations[lang]||translations.nl;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=dict[el.dataset.i18n];if(value)el.textContent=value});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const value=dict[el.dataset.i18nPlaceholder];if(value)el.placeholder=value});document.title=dict.pageTitle||translations.nl.pageTitle;document.querySelector('meta[name="description"]').content=dict.pageDescription||translations.nl.pageDescription;document.documentElement.lang=lang==='zh'?'zh-CN':lang;document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));localStorage.setItem('goed-webwerk-language',lang)}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));
applyLanguage(localStorage.getItem('goed-webwerk-language')||'nl');
const handoverDialog=document.getElementById('handover-dialog');
document.querySelector('[data-handover-open]')?.addEventListener('click',()=>handoverDialog?.showModal());
document.querySelectorAll('[data-handover-close]').forEach(btn=>btn.addEventListener('click',()=>handoverDialog?.close()));
handoverDialog?.addEventListener('click',event=>{if(event.target===handoverDialog)handoverDialog.close()});
document.getElementById('contact-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=`Website aanvraag — ${data.get('company')||data.get('name')}`;const body=[`Naam: ${data.get('name')}`,`Bedrijf: ${data.get('company')||'-'}`,`E-mail: ${data.get('email')}`,'','Aanvraag:',data.get('message')].join('\n');window.location.href=`mailto:hallo@goedwebwerk.nl?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
