const skills={
  ui:{
    category:'design',
    nl:{title:'Website UI Critic',desc:'Laat AI een website of screenshot beoordelen alsof een senior designer meekijkt.',input:'Een screenshot, URL of korte beschrijving van de pagina.',output:'Concrete ontwerpissues, prioriteiten en een verbeterplan.',prompt:`Je bent een senior UI/UX reviewer. Beoordeel de website, screenshot of pagina die ik geef op visuele hiërarchie, typografie, spacing, kleurgebruik, CTA's, vertrouwen, mobiel gedrag en algemene polish. Vermijd generieke opmerkingen. Noem eerst wat al goed werkt. Geef daarna maximaal 8 concrete problemen, gerangschikt op impact. Voor elk probleem: wat er misgaat, waarom dat merkbaar is voor de gebruiker, en precies wat je zou veranderen. Sluit af met de 5 wijzigingen die ik als eerste moet uitvoeren. Behoud de bestaande merkidentiteit tenzij die aantoonbaar het probleem veroorzaakt.`},
    en:{title:'Website UI Critic',desc:'Review a website or screenshot as if a senior product designer were looking over your shoulder.',input:'A screenshot, URL or short page description.',output:'Concrete design issues, priorities and an improvement plan.',prompt:`You are a senior UI/UX reviewer. Review the website, screenshot or page I provide for visual hierarchy, typography, spacing, color use, CTAs, trust, mobile behavior and overall polish. Avoid generic feedback. Start with what already works. Then list no more than 8 concrete issues ordered by impact. For each issue explain what is wrong, why users will notice it, and exactly what you would change. Finish with the 5 changes I should implement first. Preserve the existing brand identity unless it clearly causes the problem.`},
    zh:{title:'网站 UI 评审',desc:'让 AI 像资深产品设计师一样检查网页或截图。',input:'网页截图、URL 或页面简述。',output:'具体设计问题、优先级与修改方案。',prompt:`你是一名资深 UI/UX 评审。请检查我提供的网站、截图或页面，重点分析视觉层级、字体、间距、颜色、CTA、可信度、移动端表现和整体精致度。不要给空泛建议。先指出已经做得好的地方，再列出最多 8 个具体问题，并按影响大小排序。每个问题说明：哪里不对、为什么用户会感觉到、具体应该怎么改。最后给出最优先执行的 5 项修改。除非品牌本身明显造成问题，否则保留现有品牌识别。`}
  },
  landing:{
    category:'design',
    nl:{title:'Landing Page Designer',desc:'Van ruwe propositie naar een duidelijke landingspagina zonder typische AI-look.',input:'Product, doelgroep, belangrijkste actie en bewijs.',output:'Pagina-architectuur, copyrichting en ontwerpregels.',prompt:`Werk als conversion-focused webdesigner. Ontwerp een landingspagina voor [PRODUCT] voor [DOELGROEP]. De primaire actie is [ACTIE]. Bouw eerst de informatiehiërarchie: hero, probleem, oplossing, bewijs, voordelen, werkwijze, bezwaren, CTA. Schrijf daarna per sectie een korte inhoudsrichting en ontwerpnotities. Gebruik rustige spacing, sterke typografische hiërarchie en duidelijke contrasten. Vermijd AI-clichés zoals overmatige gradients, enorme afgeronde kaarten, willekeurige iconen en generieke slogans. Geef tot slot een mobiele volgorde en een checklist voor de eindcontrole.`},
    en:{title:'Landing Page Designer',desc:'Turn a rough proposition into a clear landing page without the usual AI look.',input:'Product, audience, primary action and proof.',output:'Page architecture, copy direction and design rules.',prompt:`Work as a conversion-focused web designer. Design a landing page for [PRODUCT] for [AUDIENCE]. The primary action is [ACTION]. First build the information hierarchy: hero, problem, solution, proof, benefits, process, objections, CTA. Then give concise content direction and design notes for each section. Use calm spacing, strong typographic hierarchy and clear contrast. Avoid AI clichés such as excessive gradients, giant rounded cards, random icons and generic slogans. Finish with a mobile content order and a final QA checklist.`},
    zh:{title:'落地页设计师',desc:'把粗略卖点整理成清晰、有质感、没有“AI味”的落地页。',input:'产品、目标用户、核心动作和可信证明。',output:'页面结构、文案方向与设计规则。',prompt:`你是一名以转化为目标的网页设计师。请为 [产品] 面向 [目标用户] 设计落地页，核心动作是 [行动]。先搭建信息层级：首屏、问题、解决方案、证明、优势、流程、疑虑处理、CTA。然后为每个部分给出简短内容方向和设计说明。使用克制的间距、清晰的字体层级和明确对比。避免常见“AI味”：滥用渐变、超大圆角卡片、无意义图标和空泛口号。最后给出移动端内容顺序和上线前检查清单。`}
  },
  copy:{
    category:'business',
    nl:{title:'Lokale Website Copywriter',desc:'Schrijft nuchtere, lokale webteksten die klanten snel begrijpen.',input:'Bedrijf, plaats, diensten, doelgroep en gewenste actie.',output:'Hero, diensten, vertrouwen, CTA en FAQ-copy.',prompt:`Schrijf Nederlandse websitecopy voor [BEDRIJF] in [PLAATS]. Diensten: [DIENSTEN]. Doelgroep: [DOELGROEP]. Gewenste actie: [ACTIE]. Schrijf alsof een goed lokaal bedrijf zelf duidelijk uitlegt wat het doet: concreet, menselijk en zonder marketingjargon. Lever: hero-kop, subkop, korte introductie, 3 dienstblokken, vertrouwen/bewijs, CTA en 5 FAQ's. Gebruik alleen feiten die ik geef en verzin geen certificaten, jaren ervaring, reviews of garanties.`},
    en:{title:'Local Website Copywriter',desc:'Writes clear local-business website copy customers can understand quickly.',input:'Business, city, services, audience and desired action.',output:'Hero, services, trust section, CTA and FAQ copy.',prompt:`Write website copy for [BUSINESS] in [CITY]. Services: [SERVICES]. Audience: [AUDIENCE]. Desired action: [ACTION]. Write like a good local business clearly explaining what it does: concrete, human and free of marketing jargon. Deliver a hero headline, subheadline, short intro, 3 service blocks, trust/proof section, CTA and 5 FAQs. Use only facts I provide and never invent certifications, years of experience, reviews or guarantees.`},
    zh:{title:'本地商家网页文案',desc:'把本地商家的服务写得清楚、自然，让客户一眼看懂。',input:'商家、城市、服务、客户群和目标动作。',output:'首屏、服务、信任、CTA 与常见问题文案。',prompt:`为位于 [城市] 的 [商家] 写网站文案。服务：[服务]。目标客户：[客户群]。希望客户执行的动作：[行动]。语气像一家靠谱的本地商家在清楚介绍自己：具体、自然，不堆营销黑话。输出：首屏标题、副标题、简短介绍、3 个服务模块、信任/证明模块、CTA 和 5 个 FAQ。只能使用我提供的事实，不得编造资质、经营年限、评价或保证。`}
  },
  dutch:{
    category:'writing',
    nl:{title:'Natuurlijk Nederlands',desc:'Maakt stijve of vertaalde tekst natuurlijker zonder de betekenis te veranderen.',input:'Een Nederlandse tekst of een vertaling naar het Nederlands.',output:'Een natuurlijke versie plus alleen belangrijke taalkeuzes.',prompt:`Herschrijf onderstaande tekst in natuurlijk Nederlands zoals dat in Nederland werkelijk wordt gebruikt. Behoud betekenis, feiten, toon en mate van formaliteit. Vermijd letterlijke vertaalstructuren, overdreven formele woorden en onnatuurlijke AI-zinnen. Maak de tekst niet bloemrijker dan nodig. Geef eerst alleen de verbeterde versie. Licht daarna maximaal 3 belangrijke wijzigingen kort toe als die echt nuttig zijn. Tekst: [TEKST]`},
    en:{title:'Natural Dutch',desc:'Makes stiff or translated Dutch sound natural without changing the meaning.',input:'Dutch text or a translation into Dutch.',output:'A natural version plus only the most useful language notes.',prompt:`Rewrite the text below into natural Dutch as actually used in the Netherlands. Preserve the meaning, facts, tone and level of formality. Avoid literal translation structures, unnecessarily formal words and unnatural AI phrasing. Do not make the text more flowery than needed. First provide only the improved Dutch version. Then explain no more than 3 important changes if they are genuinely useful. Text: [TEXT]`},
    zh:{title:'自然荷兰语',desc:'把生硬或翻译腔的荷兰语改得自然，同时保持原意。',input:'荷兰语原文或翻译成荷兰语的文本。',output:'自然版本，以及最多 3 条真正有用的语言说明。',prompt:`请把下面的文字改写成荷兰本地真实使用的自然荷兰语。保持原意、事实、语气和正式程度。避免逐字翻译结构、过度正式词汇和明显的 AI 腔。不要为了“好看”而过度润色。先只给出修改后的荷兰语版本；如确有必要，再最多解释 3 个关键修改。文本：[文本]`}
  },
  photo:{
    category:'creative',
    nl:{title:'Lightroom Photo Coach',desc:'Analyseert een foto en geeft een bewerkplan dat natuurlijk blijft.',input:'Een foto en eventueel de gewenste sfeer.',output:'Crop, exposure, WB, tone, HSL, masks en volgorde.',prompt:`Analyseer de meegestuurde foto als Lightroom-editor. Mijn doel is een geloofwaardig beeld dat zichtbaar beter is dan de opname, zonder HDR-look of zware filter. Geef alleen aanpassingen die de foto echt nodig heeft. Werk in deze volgorde: 1) crop en horizon, 2) exposure en witbalans, 3) highlights/shadows/contrast, 4) HSL indien nodig, 5) lokale masks, 6) verscherping/noise. Geef praktische richtwaarden en leg kort uit wat het visuele doel per stap is. Bescherm huidtinten en voorkom dichtgelopen schaduwen of uitgebeten hooglichten.`},
    en:{title:'Lightroom Photo Coach',desc:'Analyzes a photo and gives an edit plan that still looks natural.',input:'A photo and optionally the desired mood.',output:'Crop, exposure, WB, tone, HSL, masks and edit order.',prompt:`Analyze the attached photo as a Lightroom editor. My goal is a believable image that is clearly better than the capture, without an HDR look or heavy filter. Recommend only edits the image actually needs. Work in this order: 1) crop and horizon, 2) exposure and white balance, 3) highlights/shadows/contrast, 4) HSL if needed, 5) local masks, 6) sharpening/noise. Give practical target ranges and briefly explain the visual goal of each step. Protect skin tones and avoid crushed shadows or clipped highlights.`},
    zh:{title:'Lightroom 调色教练',desc:'分析照片并给出自然、有层次的 Lightroom 调整方案。',input:'一张照片，以及可选的目标氛围。',output:'裁切、曝光、白平衡、明暗、HSL、蒙版和调整顺序。',prompt:`请以 Lightroom 修图师的方式分析我上传的照片。目标是“明显比原片更好，但仍然真实”，不要 HDR 感和重滤镜。只建议照片真正需要的修改。按顺序输出：1）裁切与水平；2）曝光和白平衡；3）高光/阴影/对比；4）必要时的 HSL；5）局部蒙版；6）锐化/降噪。给出实用的参数范围，并简短说明每一步想达到的视觉效果。保护肤色，避免死黑阴影和爆掉的高光。`}
  },
  meeting:{
    category:'productivity',
    nl:{title:'Meeting → Actieplan',desc:'Zet notulen of transcript om in besluiten en taken zonder dingen te verzinnen.',input:'Notulen, transcript of ruwe aantekeningen.',output:'Besluiten, acties, eigenaar, deadline, risico’s en open punten.',prompt:`Zet onderstaande vergadering om in een uitvoerbaar actieplan. Gebruik uitsluitend informatie uit de bron en verzin niets. Maak secties voor: 1) genomen besluiten, 2) acties met eigenaar en deadline als die genoemd zijn, 3) open vragen, 4) risico's/blokkades, 5) punten voor de volgende vergadering. Als eigenaar of deadline ontbreekt, schrijf expliciet 'niet toegewezen' of 'geen datum genoemd'. Sluit af met een ultrakorte samenvatting van maximaal 5 regels. Bron: [NOTULEN/TRANSCRIPT]`},
    en:{title:'Meeting → Action Plan',desc:'Turns notes or transcripts into decisions and tasks without inventing anything.',input:'Meeting notes, transcript or rough notes.',output:'Decisions, actions, owners, deadlines, risks and open points.',prompt:`Turn the meeting below into an executable action plan. Use only information from the source and invent nothing. Create sections for: 1) decisions made, 2) actions with owner and deadline when stated, 3) open questions, 4) risks/blockers, 5) items for the next meeting. If an owner or deadline is missing, explicitly write 'unassigned' or 'no date stated'. Finish with an ultra-short summary of no more than 5 lines. Source: [NOTES/TRANSCRIPT]`},
    zh:{title:'会议 → 行动计划',desc:'把会议记录整理成决定和任务，不让 AI 自己脑补。',input:'会议纪要、录音转写或零散笔记。',output:'决定、任务、负责人、期限、风险与待确认事项。',prompt:`请把下面的会议内容整理成可以执行的行动计划。只能使用原始内容中的信息，不得自行补充。分为：1）已经作出的决定；2）行动项（如原文有负责人和期限则写出）；3）待确认问题；4）风险/阻塞；5）下次会议要继续处理的事项。如果没有负责人或期限，明确写“未指定”或“未提到日期”。最后用不超过 5 行做极简总结。原文：[会议纪要/转写]`}
  }
};

const ui={
nl:{back:'Websites',heroK:'AI Skills van GOED WEBWERK',hero1:'Geef AI een werkwijze.',hero2:'Niet alleen een prompt.',heroP:'Praktische, herbruikbare instructies voor werk dat je vaker doet — getest, duidelijk en direct te kopiëren.',browse:'Bekijk de skills',custom:'Skill op maat',count:'beschikbare skills',langs:'talen',price:'gratis om te starten',libK:'Skill library',libT:'Klein begonnen. Meteen bruikbaar.',libP:'Geen verzameling van duizend losse prompts. Alleen compacte werkwijzen die een duidelijke taak van begin tot eind sturen.',all:'Alles',design:'Design',business:'Business',writing:'Schrijven',creative:'Creatief',productivity:'Productiviteit',free:'Gratis',open:'Bekijk & kopieer →',customK:'Voor je eigen workflow',customT:'Laat een Skill op maat maken.',customP:'Heb je een terugkerende taak in je bedrijf? We kunnen er een vaste AI-werkwijze van maken — met jouw regels, voorbeelden en output.',customBtn:'Bespreek een Skill',input:'Wat geef je mee?',output:'Wat krijg je terug?',prompt:'Skill prompt',copy:'Kopieer',copied:'Gekopieerd',footer:'AI Skills zijn een nieuw onderdeel van GOED WEBWERK.'},
en:{back:'Websites',heroK:'AI Skills by GOED WEBWERK',hero1:'Give AI a workflow.',hero2:'Not just a prompt.',heroP:'Practical, reusable instructions for work you do more than once — tested, clear and ready to copy.',browse:'Browse skills',custom:'Custom skill',count:'available skills',langs:'languages',price:'free to start',libK:'Skill library',libT:'Start small. Make it useful.',libP:'Not a pile of a thousand random prompts. Only compact workflows that guide a clear task from start to finish.',all:'All',design:'Design',business:'Business',writing:'Writing',creative:'Creative',productivity:'Productivity',free:'Free',open:'View & copy →',customK:'For your own workflow',customT:'Have a Skill made for your work.',customP:'Have a recurring task in your business? We can turn it into a fixed AI workflow with your rules, examples and output.',customBtn:'Discuss a Skill',input:'What do you provide?',output:'What do you get?',prompt:'Skill prompt',copy:'Copy',copied:'Copied',footer:'AI Skills are a new part of GOED WEBWERK.'},
zh:{back:'网站制作',heroK:'GOED WEBWERK · AI Skills',hero1:'给 AI 一套工作方法。',hero2:'而不只是一句提示词。',heroP:'把经常重复的工作变成可复用的 AI 工作流程——经过整理、清楚、可以直接复制使用。',browse:'浏览 Skills',custom:'定制 Skill',count:'个可用 Skills',langs:'种语言',price:'目前免费',libK:'Skill 技能库',libT:'先做少，但每个都真能用。',libP:'不堆一千条零散提示词，只做能把一个明确任务从头带到尾的工作方法。',all:'全部',design:'设计',business:'商业',writing:'写作',creative:'创意',productivity:'效率',free:'免费',open:'查看并复制 →',customK:'你的专属流程',customT:'把重复工作做成自己的 Skill。',customP:'如果你的工作里有一件事总要反复做，我们可以把它整理成固定 AI 流程，带上你的规则、示例和输出格式。',customBtn:'聊聊定制 Skill',input:'需要提供什么？',output:'会得到什么？',prompt:'Skill 提示词',copy:'复制',copied:'已复制',footer:'AI Skills 是 GOED WEBWERK 新增的一项能力。'}
};

let lang=localStorage.getItem('goed-webwerk-language')||'nl';
const modal=document.getElementById('skill-dialog');
const titleEl=document.getElementById('modal-title');
const descEl=document.getElementById('modal-desc');
const inputEl=document.getElementById('modal-input');
const outputEl=document.getElementById('modal-output');
const promptEl=document.getElementById('modal-prompt');
const copyBtn=document.getElementById('copy-btn');

function applyLanguage(next){
  lang=next;localStorage.setItem('goed-webwerk-language',lang);document.documentElement.lang=lang==='zh'?'zh-CN':lang;
  document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));
  document.querySelectorAll('[data-ui]').forEach(el=>{const v=ui[lang][el.dataset.ui];if(v)el.textContent=v});
  document.querySelectorAll('[data-skill]').forEach(card=>{const s=skills[card.dataset.skill][lang];card.querySelector('[data-title]').textContent=s.title;card.querySelector('[data-desc]').textContent=s.desc});
}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyLanguage(b.dataset.lang)));

document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{
  document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');
  const c=b.dataset.filter;document.querySelectorAll('.skill-card').forEach(card=>card.hidden=c!=='all'&&card.dataset.category!==c);
}));

document.querySelectorAll('[data-open-skill]').forEach(b=>b.addEventListener('click',()=>{
  const id=b.closest('[data-skill]').dataset.skill;const s=skills[id][lang];titleEl.textContent=s.title;descEl.textContent=s.desc;inputEl.textContent=s.input;outputEl.textContent=s.output;promptEl.textContent=s.prompt;modal.showModal();
}));
document.querySelector('[data-close]').addEventListener('click',()=>modal.close());
modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
copyBtn.addEventListener('click',async()=>{await navigator.clipboard.writeText(promptEl.textContent);copyBtn.textContent=ui[lang].copied;setTimeout(()=>copyBtn.textContent=ui[lang].copy,1200)});
applyLanguage(lang);
